name: football_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  floor: ^1.4.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  http: ^1.1.2
  provider: ^6.1.1
  sqflite: ^2.3.0
  url_launcher: ^6.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  floor_generator: ^1.4.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/

